// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderSpec) DeepCopyInto(out *FyreClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderSpec.
func (in *FyreClusterProviderSpec) DeepCopy() *FyreClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderSpecList) DeepCopyInto(out *FyreClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FyreClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderSpecList.
func (in *FyreClusterProviderSpecList) DeepCopy() *FyreClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderSpecSpec) DeepCopyInto(out *FyreClusterProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderSpecSpec.
func (in *FyreClusterProviderSpecSpec) DeepCopy() *FyreClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderSpecStatus) DeepCopyInto(out *FyreClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderSpecStatus.
func (in *FyreClusterProviderSpecStatus) DeepCopy() *FyreClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderStatus) DeepCopyInto(out *FyreClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderStatus.
func (in *FyreClusterProviderStatus) DeepCopy() *FyreClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderStatusList) DeepCopyInto(out *FyreClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FyreClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderStatusList.
func (in *FyreClusterProviderStatusList) DeepCopy() *FyreClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderStatusSpec) DeepCopyInto(out *FyreClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderStatusSpec.
func (in *FyreClusterProviderStatusSpec) DeepCopy() *FyreClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreClusterProviderStatusStatus) DeepCopyInto(out *FyreClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreClusterProviderStatusStatus.
func (in *FyreClusterProviderStatusStatus) DeepCopy() *FyreClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(FyreClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderSpec) DeepCopyInto(out *FyreMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderSpec.
func (in *FyreMachineProviderSpec) DeepCopy() *FyreMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderSpecList) DeepCopyInto(out *FyreMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FyreMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderSpecList.
func (in *FyreMachineProviderSpecList) DeepCopy() *FyreMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderSpecSpec) DeepCopyInto(out *FyreMachineProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderSpecSpec.
func (in *FyreMachineProviderSpecSpec) DeepCopy() *FyreMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderSpecStatus) DeepCopyInto(out *FyreMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderSpecStatus.
func (in *FyreMachineProviderSpecStatus) DeepCopy() *FyreMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderStatus) DeepCopyInto(out *FyreMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderStatus.
func (in *FyreMachineProviderStatus) DeepCopy() *FyreMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderStatusList) DeepCopyInto(out *FyreMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FyreMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderStatusList.
func (in *FyreMachineProviderStatusList) DeepCopy() *FyreMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FyreMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderStatusSpec) DeepCopyInto(out *FyreMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderStatusSpec.
func (in *FyreMachineProviderStatusSpec) DeepCopy() *FyreMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FyreMachineProviderStatusStatus) DeepCopyInto(out *FyreMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FyreMachineProviderStatusStatus.
func (in *FyreMachineProviderStatusStatus) DeepCopy() *FyreMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(FyreMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
